# Generated by Django 4.2.4 on 2023-08-10 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=50, unique=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('a', 'Active'), ('r', 'Reject'), ('c', 'Closed')], default='u', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Proposal',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_id', models.CharField(max_length=50, unique=True)),
                ('technology_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Technology',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=200)),
                ('is_valid', models.BooleanField(default=False)),
                ('Django_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_time', models.DateTimeField()),
                ('otp_value', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Otp',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('brief', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('news_image', models.FileField(blank=True, null=True, upload_to='')),
                ('technologies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies_news', to='ideasApi.technology')),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('Investment_image', models.FileField(blank=True, null=True, upload_to='')),
                ('technologies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies_investment', to='ideasApi.technology')),
            ],
            options={
                'verbose_name_plural': 'Investment',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('meet_time', models.DateTimeField(auto_now=True)),
                ('meet_link', models.URLField()),
                ('event_image', models.FileField(blank=True, null=True, upload_to='')),
                ('technologies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies_events', to='ideasApi.technology')),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
    ]
