# Generated by Django 4.2.4 on 2023-08-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideasApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='id',
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposal_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
