# Generated by Django 4.2.4 on 2023-08-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideasApi', '0002_remove_proposal_id_alter_proposal_proposal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('r', 'Reject'), ('c', 'Closed')], default='a', max_length=1),
        ),
    ]
