# Generated by Django 4.2.4 on 2023-08-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideasApi', '0002_alter_otp_user_alter_profile_django_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='meet_time',
            field=models.DateTimeField(),
        ),
    ]
