# Generated by Django 4.2.4 on 2023-08-09 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideasApi', '0002_blacklistedtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlacklistedToken',
        ),
    ]
