# Generated by Django 4.2.4 on 2023-08-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideasApi', '0003_alter_proposal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('reject', 'Reject'), ('closed', 'Closed')], default='active', max_length=10),
        ),
    ]
